import {
  issueDataExportResponseSchema,
  publicIssueListResponseSchema,
  publicIssueOverviewSchema,
  publicPositionDataExportResponseSchema,
  publicQuestionCountsSchema,
  questionDataExportResponseSchema,
  snapshotDataExportResponseSchema,
} from "@konsensus/public-api";
export {
  demoEligibilityDirectory,
  demoEligibilityDirectoryCheckpointHistory,
  demoEligibilityDirectoryRecordProofs,
  demoQuestionVoteCheckpoints,
  demoTransparencyCheckpoint,
  demoTransparencyConsistency,
  demoTransparencyEntries,
  demoTransparencyInclusion,
  demoVerificationProofs,
  demoVoteProofBundleV3,
  demoVoteProofs,
} from "./proof-data";

const updatedAt = "2026-07-01T00:00:00.000Z";

const coastalAccessCounts = publicQuestionCountsSchema.parse({
  legalQuestionId: "question-coastal-access",
  totalCount: 12,
  directVoteCount: 12,
  publicStatementCount: 0,
  disputedCount: 0,
  choices: [
    {
      id: "choice-strengthen",
      legalQuestionId: "question-coastal-access",
      slug: "strengthen",
      label: "Strengthen the access duty",
      displayOrder: 1,
      isCounted: true,
      count: 8,
      percentage: 66.7,
      rawPercentage: 66.7,
      scorePercentage: 66.7,
    },
    {
      id: "choice-retain",
      legalQuestionId: "question-coastal-access",
      slug: "retain",
      label: "Retain the current framework",
      displayOrder: 2,
      isCounted: true,
      count: 4,
      percentage: 33.3,
      rawPercentage: 33.3,
      scorePercentage: 33.3,
    },
  ],
});

const digitalHearingsCounts = publicQuestionCountsSchema.parse({
  legalQuestionId: "question-digital-hearings",
  totalCount: 9,
  directVoteCount: 9,
  publicStatementCount: 0,
  disputedCount: 0,
  choices: [
    {
      id: "choice-presumption",
      legalQuestionId: "question-digital-hearings",
      slug: "presumption",
      label: "Create a remote-access presumption",
      displayOrder: 1,
      isCounted: true,
      count: 5,
      percentage: 55.6,
      rawPercentage: 55.6,
      scorePercentage: 55.6,
    },
    {
      id: "choice-discretion",
      legalQuestionId: "question-digital-hearings",
      slug: "discretion",
      label: "Keep case-by-case discretion",
      displayOrder: 2,
      isCounted: true,
      count: 4,
      percentage: 44.4,
      rawPercentage: 44.4,
      scorePercentage: 44.4,
    },
  ],
});

const issueRecords = [
  {
    issue: {
      id: "issue-coastal-access",
      slug: "coastal-access",
      title: "Public access across coastal land",
      shortTitle: "Coastal access",
      summary:
        "A synthetic question about the legal duty to preserve walking access across privately managed coastal land.",
      plainLanguageSummary:
        "Should the law make it easier for the public to walk across coastal land?",
      countryCode: "NZ",
      jurisdictionLabel: "Aotearoa New Zealand",
      status: "active",
      openedAt: "2026-05-12T00:00:00.000Z",
      closedAt: null,
      currentStatusText: "Open for qualified responses",
      updatedAt,
    },
    question: {
      id: "question-coastal-access",
      issueId: "issue-coastal-access",
      proceedingId: null,
      decisionId: null,
      slug: "scope-of-access-duty",
      questionText: "Should the statutory coastal-access duty be strengthened?",
      plainLanguageText:
        "Should public walking access receive stronger legal protection?",
      questionType: "binary-policy",
      status: "open",
      displayOrder: 1,
      countPolicy: "one-qualified-person-one-vote-v3",
      publishedAt: "2026-05-12T00:00:00.000Z",
      closedAt: null,
      supersedesQuestionId: null,
      updatedAt,
      counts: coastalAccessCounts,
    },
    matter: {
      id: "matter-public-land",
      slug: "public-land",
      name: "Public land and access",
      description: "Synthetic public-law questions about access to land.",
      parentMatterId: null,
      status: "active",
      updatedAt,
    },
    source: {
      id: "source-coastal-paper",
      sourceType: "consultation-paper",
      url: "https://example.test/sources/coastal-access",
      canonicalUrl: "https://example.test/sources/coastal-access",
      archiveUrl: null,
      title: "Synthetic coastal access consultation paper",
      publisher: "Open Law Aotearoa",
      authorText: null,
      languageCode: "en-NZ",
      publishedAt: "2026-04-20T00:00:00.000Z",
      capturedAt: "2026-05-01T00:00:00.000Z",
      sourceStatus: "available",
      summary: "Fictional source material for the deployable demo.",
      updatedAt,
    },
    event: {
      id: "event-coastal-consultation",
      issueId: "issue-coastal-access",
      proceedingId: null,
      eventType: "consultation-opened",
      title: "Synthetic consultation opened",
      summary: "The fictional consultation opened for public submissions.",
      occurredAt: "2026-04-20T00:00:00.000Z",
      occurredDatePrecision: "day",
      actorName: "Open Law Aotearoa",
      actorType: "reference-instance",
      importance: 1,
      updatedAt,
    },
    proceeding: {
      id: "proceeding-coastal-consultation",
      issueId: "issue-coastal-access",
      parentProceedingId: null,
      proceedingType: "public-consultation",
      bodyName: "Synthetic Coastal Access Commission",
      bodyType: "reference-body",
      caseNumber: "SYN-CA-2026",
      jurisdictionLevel: "national",
      countryCode: "NZ",
      city: null,
      partiesSummary:
        "A fictional consultation between coastal land managers and public-access groups.",
      status: "open",
      startedAt: "2026-04-20T00:00:00.000Z",
      endedAt: null,
      updatedAt,
    },
    decision: {
      id: "decision-coastal-interim",
      issueId: "issue-coastal-access",
      proceedingId: "proceeding-coastal-consultation",
      eventId: "event-coastal-consultation",
      decisionType: "interim-direction",
      decisionTitle: "Synthetic interim access direction",
      decisionSummary:
        "The fictional commission directed that both policy options remain open for consultation.",
      bodyName: "Synthetic Coastal Access Commission",
      decisionDate: "2026-05-01T00:00:00.000Z",
      decisionDatePrecision: "day",
      outcomeSummary: "Consultation continues on both options.",
      legalEffectSummary:
        "This synthetic direction has no legal effect outside the reference instance.",
      finalityStatus: "interim",
      appealStatus: null,
      enforcementStatus: null,
      updatedAt,
    },
  },
  {
    issue: {
      id: "issue-digital-hearings",
      slug: "digital-hearings",
      title: "Remote access to civil hearings",
      shortTitle: "Digital hearings",
      summary:
        "A synthetic question about when courts should make remote attendance available in civil proceedings.",
      plainLanguageSummary:
        "Should people normally be able to join civil hearings remotely?",
      countryCode: "NZ",
      jurisdictionLabel: "Aotearoa New Zealand",
      status: "active",
      openedAt: "2026-06-03T00:00:00.000Z",
      closedAt: null,
      currentStatusText: "Open for qualified responses",
      updatedAt,
    },
    question: {
      id: "question-digital-hearings",
      issueId: "issue-digital-hearings",
      proceedingId: null,
      decisionId: null,
      slug: "remote-access-presumption",
      questionText:
        "Should civil procedure presume that remote attendance is available?",
      plainLanguageText:
        "Should remote attendance normally be allowed in civil cases?",
      questionType: "binary-policy",
      status: "open",
      displayOrder: 1,
      countPolicy: "one-qualified-person-one-vote-v3",
      publishedAt: "2026-06-03T00:00:00.000Z",
      closedAt: null,
      supersedesQuestionId: null,
      updatedAt,
      counts: digitalHearingsCounts,
    },
    matter: {
      id: "matter-court-access",
      slug: "court-access",
      name: "Access to courts",
      description: "Synthetic questions about participation in proceedings.",
      parentMatterId: null,
      status: "active",
      updatedAt,
    },
    source: {
      id: "source-digital-benchbook",
      sourceType: "benchbook",
      url: "https://example.test/sources/digital-hearings",
      canonicalUrl: "https://example.test/sources/digital-hearings",
      archiveUrl: null,
      title: "Synthetic remote hearings benchbook",
      publisher: "Open Law Aotearoa",
      authorText: null,
      languageCode: "en-NZ",
      publishedAt: "2026-05-25T00:00:00.000Z",
      capturedAt: "2026-06-01T00:00:00.000Z",
      sourceStatus: "available",
      summary: "Fictional source material for the deployable demo.",
      updatedAt,
    },
    event: {
      id: "event-digital-review",
      issueId: "issue-digital-hearings",
      proceedingId: null,
      eventType: "review-opened",
      title: "Synthetic procedure review opened",
      summary: "The fictional procedure review began.",
      occurredAt: "2026-05-25T00:00:00.000Z",
      occurredDatePrecision: "day",
      actorName: "Open Law Aotearoa",
      actorType: "reference-instance",
      importance: 1,
      updatedAt,
    },
    proceeding: {
      id: "proceeding-digital-review",
      issueId: "issue-digital-hearings",
      parentProceedingId: null,
      proceedingType: "procedure-review",
      bodyName: "Synthetic Civil Procedure Committee",
      bodyType: "reference-body",
      caseNumber: "SYN-DH-2026",
      jurisdictionLevel: "national",
      countryCode: "NZ",
      city: "Wellington",
      partiesSummary:
        "A fictional review involving court users, practitioners, and accessibility groups.",
      status: "open",
      startedAt: "2026-05-25T00:00:00.000Z",
      endedAt: null,
      updatedAt,
    },
    decision: {
      id: "decision-digital-consultation",
      issueId: "issue-digital-hearings",
      proceedingId: "proceeding-digital-review",
      eventId: "event-digital-review",
      decisionType: "consultation-direction",
      decisionTitle: "Synthetic remote-access consultation direction",
      decisionSummary:
        "The fictional committee invited responses on a remote-attendance presumption.",
      bodyName: "Synthetic Civil Procedure Committee",
      decisionDate: "2026-06-01T00:00:00.000Z",
      decisionDatePrecision: "day",
      outcomeSummary: "The remote-access question was opened for responses.",
      legalEffectSummary:
        "This synthetic direction is illustrative and creates no real procedural rule.",
      finalityStatus: "consultative",
      appealStatus: null,
      enforcementStatus: null,
      updatedAt,
    },
  },
] as const;

export const demoIssueList = publicIssueListResponseSchema.parse({
  issues: issueRecords.map(({ issue, matter, question, source, event }) => ({
    ...issue,
    questionCount: 1,
    matterNames: [matter.name],
    matterSlugs: [matter.slug],
    positionCount: question.counts.totalCount,
    sourceCount: 1,
    imagePath: null,
    firstTimelineEventAt: event.occurredAt,
    latestTimelineEventAt: event.occurredAt,
    headlineQuestion: {
      id: question.id,
      slug: question.slug,
      questionText: question.questionText,
    },
    headlineCounts: question.counts,
  })),
});

export const demoIssueOverviews = Object.fromEntries(
  issueRecords.map(
    ({ issue, matter, question, source, event, proceeding, decision }) => [
      issue.slug,
      publicIssueOverviewSchema.parse({
        issue,
        matters: [matter],
        questions: [question],
        events: [event],
        proceedings: [proceeding],
        decisions: [decision],
        sources: [source],
      }),
    ],
  ),
);

export const demoQuestionCounts = Object.fromEntries(
  issueRecords.map(({ question }) => [question.id, question.counts]),
);

export const demoDataExports = {
  issues: issueDataExportResponseSchema.parse({
    issues: issueRecords.map(({ issue }) => issue),
    limit: 100,
    offset: 0,
    total: issueRecords.length,
  }),
  questions: questionDataExportResponseSchema.parse({
    questions: issueRecords.map(
      ({ question: { counts: _counts, ...question } }) => question,
    ),
    choices: [
      {
        id: "choice-strengthen",
        legalQuestionId: "question-coastal-access",
        slug: "strengthen",
        label: "Strengthen the access duty",
        shortLabel: "Strengthen",
        description: "Strengthen the statutory public-access duty.",
        semanticCode: "support",
        displayOrder: 1,
        isCounted: true,
        isDefaultUnclear: false,
      },
      {
        id: "choice-retain",
        legalQuestionId: "question-coastal-access",
        slug: "retain",
        label: "Retain the current framework",
        shortLabel: "Retain",
        description: "Retain the current statutory framework.",
        semanticCode: "oppose",
        displayOrder: 2,
        isCounted: true,
        isDefaultUnclear: false,
      },
      {
        id: "choice-presumption",
        legalQuestionId: "question-digital-hearings",
        slug: "presumption",
        label: "Create a remote-access presumption",
        shortLabel: "Presumption",
        description: "Presume that remote attendance is available.",
        semanticCode: "support",
        displayOrder: 1,
        isCounted: true,
        isDefaultUnclear: false,
      },
      {
        id: "choice-discretion",
        legalQuestionId: "question-digital-hearings",
        slug: "discretion",
        label: "Keep case-by-case discretion",
        shortLabel: "Discretion",
        description: "Keep the decision with the presiding court.",
        semanticCode: "oppose",
        displayOrder: 2,
        isCounted: true,
        isDefaultUnclear: false,
      },
    ],
    limit: 100,
    offset: 0,
    total: issueRecords.length,
  }),
  snapshots: snapshotDataExportResponseSchema.parse({
    snapshots: [],
    snapshotChoiceCounts: [],
    limit: 100,
    offset: 0,
    total: 0,
  }),
  "public-positions": publicPositionDataExportResponseSchema.parse({
    positions: [],
    limit: 100,
    offset: 0,
    total: 0,
  }),
};
